// 出題データ。文章を増やすときは、ここに { text, meaning, category } を追加します。
// text は小文字の英語と半角スペースだけにすると、タイピングしやすくなります。
window.CHILL_TYPING_PHRASES = [
  { text: "actions speak louder than words", meaning: "行動は言葉よりも雄弁である", category: "PROVERBS" },
  { text: "a picture is worth a thousand words", meaning: "百聞は一見にしかず", category: "PROVERBS" },
  { text: "better late than never", meaning: "遅くても、やらないよりはまし", category: "PROVERBS" },
  { text: "every cloud has a silver lining", meaning: "どんな困難にも希望の光がある", category: "PROVERBS" },
  { text: "practice makes perfect", meaning: "練習が上達を生む", category: "PROVERBS" },
  { text: "where there is a will there is a way", meaning: "意志あるところに道は開ける", category: "PROVERBS" },
  { text: "the early bird catches the worm", meaning: "早起きは三文の得", category: "PROVERBS" },
  { text: "two heads are better than one", meaning: "三人寄れば文殊の知恵", category: "PROVERBS" },
  { text: "when in rome do as the romans do", meaning: "郷に入っては郷に従え", category: "PROVERBS" },
  { text: "you reap what you sow", meaning: "自分の行いは自分に返ってくる", category: "PROVERBS" },
  { text: "look before you leap", meaning: "跳ぶ前によく見る、軽率に行動しない", category: "PROVERBS" },
  { text: "the pen is mightier than the sword", meaning: "ペンは剣よりも強し", category: "PROVERBS" },
  { text: "all that glitters is not gold", meaning: "輝くものがすべて金とは限らない", category: "PROVERBS" },
  { text: "necessity is the mother of invention", meaning: "必要は発明の母", category: "PROVERBS" },
  { text: "a friend in need is a friend indeed", meaning: "困ったときの友こそ真の友", category: "PROVERBS" },
  { text: "honesty is the best policy", meaning: "正直は最善の策", category: "PROVERBS" },
  { text: "time is money", meaning: "時は金なり", category: "PROVERBS" },
  { text: "knowledge is power", meaning: "知識は力なり", category: "PROVERBS" },
  { text: "slow and steady wins the race", meaning: "ゆっくり着実な者が競争に勝つ", category: "PROVERBS" },
  { text: "fortune favors the bold", meaning: "幸運は勇者に味方する", category: "PROVERBS" },
  { text: "it is never too late to learn", meaning: "学ぶのに遅すぎることはない", category: "WISDOM" },
  { text: "the journey is the reward", meaning: "旅そのものが報いである", category: "WISDOM" },
  { text: "less is more", meaning: "少ない方が豊かなこともある", category: "WISDOM" },
  { text: "every day is a fresh start", meaning: "毎日が新しい始まり", category: "WISDOM" },
  { text: "small steps every day", meaning: "毎日の小さな一歩", category: "WISDOM" },
  { text: "good things take time", meaning: "良いものには時間がかかる", category: "WISDOM" },
  { text: "enjoy the little things", meaning: "小さなことを楽しもう", category: "CHILL WORDS" },
  { text: "take a breath and begin again", meaning: "ひと息ついて、もう一度始めよう", category: "CHILL WORDS" },
  { text: "let your thoughts drift like clouds", meaning: "思考を雲のように漂わせよう", category: "MINDFUL" },
  { text: "a calm mind brings inner strength", meaning: "穏やかな心は内なる強さをもたらす", category: "MINDFUL" },
  { text: "be present in this moment", meaning: "この瞬間に意識を向けよう", category: "MINDFUL" },
  { text: "kindness costs nothing", meaning: "親切にお金はかからない", category: "GOOD VIBES" },
  { text: "a smile can brighten the darkest day", meaning: "笑顔は暗い日も明るくできる", category: "GOOD VIBES" },
  { text: "share joy and it will grow", meaning: "喜びは分かち合うと大きくなる", category: "GOOD VIBES" },
  { text: "home is where the heart is", meaning: "心のある場所が我が家", category: "COZY LIFE" },
  { text: "there is no place like home", meaning: "我が家に勝る場所はない", category: "COZY LIFE" },
  { text: "a warm cup of tea solves many things", meaning: "温かいお茶は多くのことを和らげる", category: "TEA BREAK" },
  { text: "rainy days are made for cozy rooms", meaning: "雨の日は居心地のよい部屋のためにある", category: "RAINY DAY" },
  { text: "the moon is bright above the quiet town", meaning: "静かな町の上で月が明るく輝く", category: "NIGHT TIME" },
  { text: "stars shine softly through the window", meaning: "星が窓越しにやさしく輝く", category: "NIGHT TIME" },
  { text: "books and tea make a perfect afternoon", meaning: "本とお茶は完璧な午後を作る", category: "TEA BREAK" },
  { text: "every key brings your dream room closer", meaning: "一打ごとに理想の部屋へ近づく", category: "CHILL WORDS" },
];
